app_name: Priyo Shikkhaloy
app_subtitle: Jobs Preparation & Learning App
app_download: https://apps.apple.com/us/app/flashtex-flashcards/id1534437697
app_github: https://github.com/mikakruschel/app-landing-page
app_id: 1534437697
email: mail@kruschel.dev
app_icon: /assets/icon.jpg
favicon: /assets/icon.jpg

made_by: // Made by [Amirul Sizan](https://amirulsizan.live)

links:
  - title: AppStore Connect Widget
    url: https://ac-widget.xyz

app_description: |
    Priyo Shikkhaloy is a Bangladeshi EdTech startup based on mobile app for students to access digital education.

Basically Priyo Shikkhaloy is a jobs preparation and learning apps in Bangladesh that offers a wide range of educational resources and job-related materials, such as smart notes, video lectures, practice exams, job circulars, and career guidances, to help individuals prepare for job interviews and exams. The app covers various subjects and skills, including general knowledge, English language and other genres for job preparation.
Priyo Shikkhaloy creates the best edu-environment for job seekers and learner.
Never stop learning.

####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

plugins:
  - jekyll-postcss

exclude:
  - Gemfile
  - Gemfile.lock
  - package-lock.json
  - README.md
  - postcss.config.js
  - .gitignore
  - node_modules

markdown: kramdown

collections:
  pages:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: "assets/screenshots"
    values:
      screenshot: true
