app_name: Priyo Shikkhaloy
app_subtitle: Jobs Preparation & Learning App
app_download: https://apps.apple.com/us/app/flashtex-flashcards/id1534437697
app_github: https://github.com/mikakruschel/app-landing-page
app_id: 1534437697
email: mail@kruschel.dev
app_icon: /assets/icon.jpg
favicon: /assets/icon.jpg

made_by: // Made by [Amirul Sizan](https://amirulsizan.live)

links:
  - title: AppStore Connect Widget
    url: https://ac-widget.xyz

app_description: |
    Priyo Shikkhaloy is a Bangladeshi EdTech startup based on mobile app for students to access digital education.

Basically Priyo Shikkhaloy is a jobs preparation and learning apps in Bangladesh that offers a wide range of educational resources and job-related materials, such as smart notes, video lectures, practice exams, job circulars, and career guidances, to help individuals prepare for job interviews and exams. The app covers various subjects and skills, including general knowledge, English language and other genres for job preparation.

Key Features –

Course Plan: A structured outline or syllabus that outlines the learning objectives, topics to be covered, assessments, and other details of a course. It provides a roadmap for learners to follow throughout the duration of the course.

Model Test: Model tests are designed to help individuals prepare for the actual test by giving you an opportunity to become familiar with the types of questions you may encounter and the format in which you are presented. About 50k questions is ready for your hundred percent preparation for you.

Question Bank: Over 100k past questions from different job exam and BCS. It gives you the vast idea about question pattern and topic.

Lecture Sheet: There are smart notes of important topics in the lecture sheet section. Lecture sheets made by the country's best experienced mentors will be uploaded in this section as much as necessary, which is completely different from the traditional market books.

Quiz Section: In this section, you can learn with different interactive quiz games. On the other hand, you will get reward points as soon as you cross every level and you will get excellent gifts using the points earned.

Current Affairs: This section will keep you updated on recent issues at home and abroad. Fresh updates every month will be added to this section. The recent questions that come in the recruitment test or admission exam can be easily answered.

Job Circular: This section will be one of the ways for job seekers to stay updated about various job notifications. Everyone who installs favorite educational apps will get these updates for free. Whenever there is a circular, the notification will appear in your smartphone.

Blog: This feature has rich blogs about career tips, how to be more successful, experience sharing and caring stories of experiences, new people getting into trouble and ways to overcome it.

Bookshop: The attractive feature will include books written by the country's best popular authors, video courses of experienced mentors, journals and modern edu e-shops of various educational materials.

There will also be Age Calculator feature to find out your age at the time of applying for a job, Translation feature to translate local and foreign languages, bookmark options to read important questions at the time of time, and the use of various excellent educational technologies.

We assured that, Priyo Shikkhaloy creates the best edu-environment for job seekers and learner.
Never stop learning.

####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

plugins:
  - jekyll-postcss

exclude:
  - Gemfile
  - Gemfile.lock
  - package-lock.json
  - README.md
  - postcss.config.js
  - .gitignore
  - node_modules

markdown: kramdown

collections:
  pages:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: "assets/screenshots"
    values:
      screenshot: true
